// AUTO-GENERATED by scripts/sync-claude-model-artifacts.ts
// Do not edit manually - run 'bun run scripts/sync-claude-model-artifacts.ts'

import type { ModelPricing } from "./types";

export const CLAUDE_MODEL_PRICING: Record<string, ModelPricing> = {
  "claude-opus-4-7": { inputPerMillion: 15, outputPerMillion: 75, cacheReadPerMillion: 1.5, cacheWritePerMillion: 18.75 },
  "claude-opus-4-6": { inputPerMillion: 15, outputPerMillion: 75, cacheReadPerMillion: 1.5, cacheWritePerMillion: 18.75 },
  "claude-sonnet-4-6": { inputPerMillion: 3, outputPerMillion: 15, cacheReadPerMillion: 0.3, cacheWritePerMillion: 3.75 },
  "claude-opus-4-5-20251101": { inputPerMillion: 15, outputPerMillion: 75, cacheReadPerMillion: 1.5, cacheWritePerMillion: 18.75 },
  "claude-sonnet-4-5-20250929": { inputPerMillion: 3, outputPerMillion: 15, cacheReadPerMillion: 0.3, cacheWritePerMillion: 3.75 },
  "claude-haiku-4-5-20251001": { inputPerMillion: 0.8, outputPerMillion: 4, cacheReadPerMillion: 0.08, cacheWritePerMillion: 1 },
};
