// AUTO-GENERATED by scripts/sync-codex-models.ts
// Do not edit manually - run 'bun run scripts/sync-codex-models.ts' to update

import type { AgentCatalogEntry } from "../../agent-catalog";

export interface CodexModelEntry extends AgentCatalogEntry {
  /** Whether this model is hidden from the default picker */
  hidden?: boolean;
  /** Whether this is the default model */
  isDefault?: boolean;
  /** Model ID to upgrade to (if deprecated) */
  upgrade?: string;
  /** Input modalities supported */
  inputModalities?: string[];
}

/**
 * Full Codex model catalog extracted from codex app-server.
 * Includes all models (visible and hidden).
 */
export const CODEX_CATALOG_GENERATED: CodexModelEntry[] = [
  {
    "name": "codex/gpt-5.2",
    "displayName": "gpt-5.2",
    "description": "Optimized for professional work and long-running agents.",
    "vendor": "openai",
    "requiredApiKeys": [
      "OPENAI_API_KEY",
      "CODEX_AUTH_JSON"
    ],
    "tier": "paid",
    "tags": [
      "upgradeable",
      "reasoning"
    ],
    "hidden": false,
    "isDefault": false,
    "defaultVariant": "medium",
    "variants": [
      {
        "id": "low",
        "displayName": "Low",
        "description": "Balances speed with some reasoning; useful for straightforward queries and short explanations"
      },
      {
        "id": "medium",
        "displayName": "Medium",
        "description": "Provides a solid balance of reasoning depth and latency for general-purpose tasks"
      },
      {
        "id": "high",
        "displayName": "High",
        "description": "Maximizes reasoning depth for complex or ambiguous problems"
      },
      {
        "id": "xhigh",
        "displayName": "Extra High",
        "description": "Extra high reasoning for complex problems"
      }
    ],
    "upgrade": "gpt-5.4",
    "inputModalities": [
      "text",
      "image"
    ]
  },
  {
    "name": "codex/gpt-5.3-codex",
    "displayName": "gpt-5.3-codex",
    "description": "Coding-optimized model.",
    "vendor": "openai",
    "requiredApiKeys": [
      "OPENAI_API_KEY",
      "CODEX_AUTH_JSON"
    ],
    "tier": "paid",
    "tags": [
      "upgradeable",
      "reasoning"
    ],
    "hidden": false,
    "isDefault": false,
    "defaultVariant": "medium",
    "variants": [
      {
        "id": "low",
        "displayName": "Low",
        "description": "Fast responses with lighter reasoning"
      },
      {
        "id": "medium",
        "displayName": "Medium",
        "description": "Balances speed and reasoning depth for everyday tasks"
      },
      {
        "id": "high",
        "displayName": "High",
        "description": "Greater reasoning depth for complex problems"
      },
      {
        "id": "xhigh",
        "displayName": "Extra High",
        "description": "Extra high reasoning depth for complex problems"
      }
    ],
    "upgrade": "gpt-5.4",
    "inputModalities": [
      "text",
      "image"
    ]
  },
  {
    "name": "codex/gpt-5.4",
    "displayName": "gpt-5.4",
    "description": "Strong model for everyday coding.",
    "vendor": "openai",
    "requiredApiKeys": [
      "OPENAI_API_KEY",
      "CODEX_AUTH_JSON"
    ],
    "tier": "paid",
    "tags": [
      "reasoning"
    ],
    "hidden": false,
    "isDefault": false,
    "defaultVariant": "xhigh",
    "variants": [
      {
        "id": "low",
        "displayName": "Low",
        "description": "Fast responses with lighter reasoning"
      },
      {
        "id": "medium",
        "displayName": "Medium",
        "description": "Balances speed and reasoning depth for everyday tasks"
      },
      {
        "id": "high",
        "displayName": "High",
        "description": "Greater reasoning depth for complex problems"
      },
      {
        "id": "xhigh",
        "displayName": "Extra High",
        "description": "Extra high reasoning depth for complex problems"
      }
    ],
    "inputModalities": [
      "text",
      "image"
    ]
  },
  {
    "name": "codex/gpt-5.4-mini",
    "displayName": "GPT-5.4-Mini",
    "description": "Small, fast, and cost-efficient model for simpler coding tasks.",
    "vendor": "openai",
    "requiredApiKeys": [
      "OPENAI_API_KEY",
      "CODEX_AUTH_JSON"
    ],
    "tier": "paid",
    "tags": [
      "reasoning"
    ],
    "hidden": false,
    "isDefault": false,
    "defaultVariant": "medium",
    "variants": [
      {
        "id": "low",
        "displayName": "Low",
        "description": "Fast responses with lighter reasoning"
      },
      {
        "id": "medium",
        "displayName": "Medium",
        "description": "Balances speed and reasoning depth for everyday tasks"
      },
      {
        "id": "high",
        "displayName": "High",
        "description": "Greater reasoning depth for complex problems"
      },
      {
        "id": "xhigh",
        "displayName": "Extra High",
        "description": "Extra high reasoning depth for complex problems"
      }
    ],
    "inputModalities": [
      "text",
      "image"
    ]
  },
  {
    "name": "codex/gpt-5.5",
    "displayName": "GPT-5.5",
    "description": "Frontier model for complex coding, research, and real-world work.",
    "vendor": "openai",
    "requiredApiKeys": [
      "OPENAI_API_KEY",
      "CODEX_AUTH_JSON"
    ],
    "tier": "paid",
    "tags": [
      "default",
      "reasoning"
    ],
    "hidden": false,
    "isDefault": true,
    "defaultVariant": "medium",
    "variants": [
      {
        "id": "low",
        "displayName": "Low",
        "description": "Fast responses with lighter reasoning"
      },
      {
        "id": "medium",
        "displayName": "Medium",
        "description": "Balances speed and reasoning depth for everyday tasks"
      },
      {
        "id": "high",
        "displayName": "High",
        "description": "Greater reasoning depth for complex problems"
      },
      {
        "id": "xhigh",
        "displayName": "Extra High",
        "description": "Extra high reasoning depth for complex problems"
      }
    ],
    "inputModalities": [
      "text",
      "image"
    ]
  },
  {
    "name": "codex/codex-auto-review",
    "displayName": "Codex Auto Review",
    "description": "Automatic approval review model for Codex.",
    "vendor": "openai",
    "requiredApiKeys": [
      "OPENAI_API_KEY",
      "CODEX_AUTH_JSON"
    ],
    "tier": "paid",
    "tags": [
      "hidden",
      "reasoning"
    ],
    "hidden": true,
    "isDefault": false,
    "defaultVariant": "medium",
    "variants": [
      {
        "id": "low",
        "displayName": "Low",
        "description": "Fast responses with lighter reasoning"
      },
      {
        "id": "medium",
        "displayName": "Medium",
        "description": "Balances speed and reasoning depth for everyday tasks"
      },
      {
        "id": "high",
        "displayName": "High",
        "description": "Greater reasoning depth for complex problems"
      },
      {
        "id": "xhigh",
        "displayName": "Extra High",
        "description": "Extra high reasoning depth for complex problems"
      }
    ],
    "inputModalities": [
      "text",
      "image"
    ]
  }
];

/**
 * Visible models only (for default UI display)
 */
export const CODEX_VISIBLE_MODELS = CODEX_CATALOG_GENERATED.filter(m => !m.hidden);

/**
 * Get the default Codex model
 */
export function getDefaultCodexModel(): CodexModelEntry | undefined {
  return CODEX_CATALOG_GENERATED.find(m => m.isDefault);
}

/**
 * Get model by name
 */
export function getCodexModel(name: string): CodexModelEntry | undefined {
  return CODEX_CATALOG_GENERATED.find(m => m.name === name || m.name === `codex/${name}`);
}
