import type { AgentCatalogEntry } from "../../agent-catalog";

export const CODEX_CATALOG: AgentCatalogEntry[] = [
  // GPT-5.3-codex variants
  {
    name: "codex/gpt-5.3-codex-xhigh",
    displayName: "GPT-5.3 Codex (XHigh)",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
    tags: ["latest", "reasoning"],
  },
  {
    name: "codex/gpt-5.3-codex-high",
    displayName: "GPT-5.3 Codex (High)",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
    tags: ["reasoning"],
  },
  {
    name: "codex/gpt-5.3-codex-medium",
    displayName: "GPT-5.3 Codex (Medium)",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
    tags: ["reasoning"],
  },
  {
    name: "codex/gpt-5.3-codex-low",
    displayName: "GPT-5.3 Codex (Low)",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
    tags: ["reasoning"],
  },
  {
    name: "codex/gpt-5.3-codex",
    displayName: "GPT-5.3 Codex",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
  },
  // GPT-5.2-codex variants
  {
    name: "codex/gpt-5.2-codex-xhigh",
    displayName: "GPT-5.2 Codex (XHigh)",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
    tags: ["reasoning"],
  },
  {
    name: "codex/gpt-5.2-codex-high",
    displayName: "GPT-5.2 Codex (High)",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
    tags: ["reasoning"],
  },
  {
    name: "codex/gpt-5.2-codex-medium",
    displayName: "GPT-5.2 Codex (Medium)",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
    tags: ["reasoning"],
  },
  {
    name: "codex/gpt-5.2-codex-low",
    displayName: "GPT-5.2 Codex (Low)",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
    tags: ["reasoning"],
  },
  {
    name: "codex/gpt-5.2-codex",
    displayName: "GPT-5.2 Codex",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
  },
  // GPT-5.1-codex-max variants
  {
    name: "codex/gpt-5.1-codex-max-xhigh",
    displayName: "GPT-5.1 Codex Max (XHigh)",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
    tags: ["reasoning"],
  },
  {
    name: "codex/gpt-5.1-codex-max-high",
    displayName: "GPT-5.1 Codex Max (High)",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
    tags: ["reasoning"],
  },
  {
    name: "codex/gpt-5.1-codex-max-medium",
    displayName: "GPT-5.1 Codex Max (Medium)",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
    tags: ["reasoning"],
  },
  {
    name: "codex/gpt-5.1-codex-max-low",
    displayName: "GPT-5.1 Codex Max (Low)",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
    tags: ["reasoning"],
  },
  {
    name: "codex/gpt-5.1-codex-max",
    displayName: "GPT-5.1 Codex Max",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
  },
  // GPT-5.1 variants
  {
    name: "codex/gpt-5.1-codex-high",
    displayName: "GPT-5.1 Codex (High)",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
    tags: ["reasoning"],
  },
  {
    name: "codex/gpt-5.1-codex",
    displayName: "GPT-5.1 Codex",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
  },
  {
    name: "codex/gpt-5.1-codex-mini",
    displayName: "GPT-5.1 Codex Mini",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
  },
  {
    name: "codex/gpt-5.1",
    displayName: "GPT-5.1",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
  },
  // GPT-5.2 base variants
  {
    name: "codex/gpt-5.2",
    displayName: "GPT-5.2",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
  },
  {
    name: "codex/gpt-5.2-xhigh",
    displayName: "GPT-5.2 (XHigh)",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
    tags: ["reasoning"],
  },
  {
    name: "codex/gpt-5.2-high",
    displayName: "GPT-5.2 (High)",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
    tags: ["reasoning"],
  },
  {
    name: "codex/gpt-5.2-medium",
    displayName: "GPT-5.2 (Medium)",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
    tags: ["reasoning"],
  },
  {
    name: "codex/gpt-5.2-low",
    displayName: "GPT-5.2 (Low)",
    vendor: "openai",
    requiredApiKeys: ["OPENAI_API_KEY", "CODEX_AUTH_JSON"],
    tier: "paid",
    tags: ["reasoning"],
  },
];
