// AUTO-GENERATED by scripts/sync-claude-model-artifacts.ts
// Do not edit manually - run 'bun run scripts/sync-claude-model-artifacts.ts'

package models

type Pricing struct {
	InputPer1M  float64
	OutputPer1M float64
}

const RecommendedClaudeAgent = "claude/opus-4.7"

var ClaudeLocalAgentToModelID = map[string]string{
	"claude/opus-4.7":   "claude-opus-4-7",
	"claude/opus-4.6":   "claude-opus-4-6",
	"claude/sonnet-4.6": "claude-sonnet-4-6",
	"claude/opus-4.5":   "claude-opus-4-5-20251101",
	"claude/sonnet-4.5": "claude-sonnet-4-5-20250929",
	"claude/haiku-4.5":  "claude-haiku-4-5-20251001",
}

var ClaudeEffortVariants = map[string]struct{}{
	"low":    {},
	"medium": {},
	"high":   {},
	"max":    {},
}

var ClaudeEffortCapableAgents = map[string]struct{}{
	"claude/opus-4.7": {},
	"claude/opus-4.6": {},
}

var ClaudePricingByAgent = map[string]Pricing{
	"claude/opus-4.7":   {InputPer1M: 15.0, OutputPer1M: 75.0},
	"claude/opus-4.6":   {InputPer1M: 15.0, OutputPer1M: 75.0},
	"claude/sonnet-4.6": {InputPer1M: 3.0, OutputPer1M: 15.0},
	"claude/opus-4.5":   {InputPer1M: 15.0, OutputPer1M: 75.0},
	"claude/sonnet-4.5": {InputPer1M: 3.0, OutputPer1M: 15.0},
	"claude/haiku-4.5":  {InputPer1M: 0.8, OutputPer1M: 4.0},
}

var ClaudePricingByNativeModel = map[string]Pricing{
	"claude-opus-4-7":            {InputPer1M: 15.0, OutputPer1M: 75.0},
	"claude-opus-4-6":            {InputPer1M: 15.0, OutputPer1M: 75.0},
	"claude-sonnet-4-6":          {InputPer1M: 3.0, OutputPer1M: 15.0},
	"claude-opus-4-5-20251101":   {InputPer1M: 15.0, OutputPer1M: 75.0},
	"claude-sonnet-4-5-20250929": {InputPer1M: 3.0, OutputPer1M: 15.0},
	"claude-haiku-4-5-20251001":  {InputPer1M: 0.8, OutputPer1M: 4.0},
}
