// Auto-generated by scripts/update-opencode-free-models.mjs
// Source: https://opencode.ai/zen/v1/models
// Last updated: 2026-02-17T15:55:28.040Z
export const OPENCODE_FREE_MODEL_IDS = [
  "big-pickle",
  "glm-5-free",
  "kimi-k2.5-free",
  "minimax-m2.1-free",
  "minimax-m2.5-free",
  "trinity-large-preview-free"
] as const;

export type OpencodeFreeModelId = typeof OPENCODE_FREE_MODEL_IDS[number];
