// Auto-generated by scripts/update-opencode-free-models.mjs
// Source: https://opencode.ai/zen/v1/models
// Last updated: 2026-01-07T12:29:17.547Z
export const OPENCODE_FREE_MODEL_IDS = [
  "big-pickle",
  "glm-4.7-free",
  "grok-code",
  "minimax-m2.1-free"
] as const;

export type OpencodeFreeModelId = typeof OPENCODE_FREE_MODEL_IDS[number];
