#!/usr/bin/env bun
/**
 * Claude Model Artifact Sync
 *
 * Uses the shared Claude manifest as the single source of truth and generates:
 * 1. devsh Go Claude metadata (`internal/models/claude_generated.go`)
 * 2. TypeScript SDK Claude pricing (`agent-sdk/src/claude-pricing.generated.ts`)
 * 3. Python SDK Claude pricing (`agent-sdk-python/.../claude_pricing_generated.py`)
 *
 * Usage:
 *   bun run scripts/sync-claude-model-artifacts.ts
 *   bun run scripts/sync-claude-model-artifacts.ts --check
 */

import * as fs from "node:fs";
import * as path from "node:path";
import { spawnSync } from "node:child_process";
import {
  CLAUDE_CURATED_MODELS,
  CLAUDE_EFFORT_VARIANTS,
  DEFAULT_CLAUDE_AGENT_NAME,
} from "../packages/shared/src/providers/anthropic/manifest";

const CHECK_ONLY = process.argv.includes("--check");

function formatGoFloat(value: number): string {
  if (Number.isInteger(value)) {
    return `${value}.0`;
  }
  return value.toString();
}

function generateDevshClaudeModelsGo(): string {
  const localAgentMap = CLAUDE_CURATED_MODELS.map(
    (entry) => `\t"${entry.agentName}": "${entry.nativeModelId}",`,
  ).join("\n");

  const effortVariants = CLAUDE_EFFORT_VARIANTS.map(
    (variant) => `\t"${variant.id}": {},`,
  ).join("\n");

  const effortAgents = CLAUDE_CURATED_MODELS.filter((entry) => entry.supportsEffort)
    .map((entry) => `\t"${entry.agentName}": {},`)
    .join("\n");

  const pricingByAgent = CLAUDE_CURATED_MODELS.map((entry) => {
    const { inputPerMillion, outputPerMillion } = entry.pricing;
    return `\t"${entry.agentName}": {InputPer1M: ${formatGoFloat(inputPerMillion)}, OutputPer1M: ${formatGoFloat(outputPerMillion)}},`;
  }).join("\n");

  const pricingByNativeModel = CLAUDE_CURATED_MODELS.map((entry) => {
    const { inputPerMillion, outputPerMillion } = entry.pricing;
    return `\t"${entry.nativeModelId}": {InputPer1M: ${formatGoFloat(inputPerMillion)}, OutputPer1M: ${formatGoFloat(outputPerMillion)}},`;
  }).join("\n");

  return `// AUTO-GENERATED by scripts/sync-claude-model-artifacts.ts
// Do not edit manually - run 'bun run scripts/sync-claude-model-artifacts.ts'

package models

type Pricing struct {
\tInputPer1M  float64
\tOutputPer1M float64
}

const RecommendedClaudeAgent = "${DEFAULT_CLAUDE_AGENT_NAME}"

var ClaudeLocalAgentToModelID = map[string]string{
${localAgentMap}
}

var ClaudeEffortVariants = map[string]struct{}{
${effortVariants}
}

var ClaudeEffortCapableAgents = map[string]struct{}{
${effortAgents}
}

var ClaudePricingByAgent = map[string]Pricing{
${pricingByAgent}
}

var ClaudePricingByNativeModel = map[string]Pricing{
${pricingByNativeModel}
}
`;
}

function formatGoSource(source: string): string {
  const result = spawnSync("gofmt", {
    input: source,
    encoding: "utf8",
  });
  if (result.status !== 0) {
    const stderr = result.stderr?.toString().trim() ?? "unknown gofmt error";
    throw new Error(`gofmt failed: ${stderr}`);
  }
  return result.stdout;
}

function generateAgentSdkClaudePricingTs(): string {
  const entries = CLAUDE_CURATED_MODELS.map((entry) => {
    const pricing = entry.pricing;
    const parts = [
      `inputPerMillion: ${pricing.inputPerMillion}`,
      `outputPerMillion: ${pricing.outputPerMillion}`,
    ];
    if (pricing.cacheReadPerMillion !== undefined) {
      parts.push(`cacheReadPerMillion: ${pricing.cacheReadPerMillion}`);
    }
    if (pricing.cacheWritePerMillion !== undefined) {
      parts.push(`cacheWritePerMillion: ${pricing.cacheWritePerMillion}`);
    }
    return `  "${entry.nativeModelId}": { ${parts.join(", ")} },`;
  }).join("\n");

  return `// AUTO-GENERATED by scripts/sync-claude-model-artifacts.ts
// Do not edit manually - run 'bun run scripts/sync-claude-model-artifacts.ts'

import type { ModelPricing } from "./types";

export const CLAUDE_MODEL_PRICING: Record<string, ModelPricing> = {
${entries}
};
`;
}

function generateAgentSdkClaudePricingPy(): string {
  const entries = CLAUDE_CURATED_MODELS.map((entry) => {
    const pricing = entry.pricing;
    const parts = [
      `input_per_million: ${pricing.inputPerMillion}`,
      `output_per_million: ${pricing.outputPerMillion}`,
    ];
    if (pricing.cacheReadPerMillion !== undefined) {
      parts.push(`cache_read_per_million: ${pricing.cacheReadPerMillion}`);
    }
    if (pricing.cacheWritePerMillion !== undefined) {
      parts.push(`cache_write_per_million: ${pricing.cacheWritePerMillion}`);
    }
    return `    "${entry.nativeModelId}": {${parts.join(", ")}},`;
  }).join("\n");

  return `# AUTO-GENERATED by scripts/sync-claude-model-artifacts.ts
# Do not edit manually - run 'bun run scripts/sync-claude-model-artifacts.ts'

from __future__ import annotations

from typing import TypedDict


class ClaudePricingEntry(TypedDict, total=False):
    input_per_million: float
    output_per_million: float
    cache_read_per_million: float
    cache_write_per_million: float


CLAUDE_MODEL_PRICING: dict[str, ClaudePricingEntry] = {
${entries}
}
`;
}

function writeOrCheckFile(filePath: string, content: string): boolean {
  const current = fs.existsSync(filePath) ? fs.readFileSync(filePath, "utf8") : "";
  if (current === content) {
    return true;
  }

  if (CHECK_ONLY) {
    console.error(`[sync-claude-model-artifacts] Drift detected: ${filePath}`);
    return false;
  }

  fs.mkdirSync(path.dirname(filePath), { recursive: true });
  fs.writeFileSync(filePath, content);
  console.log(`[sync-claude-model-artifacts] Wrote ${filePath}`);
  return true;
}

function main(): void {
  const repoRoot = path.join(import.meta.dirname, "..");

  const targets: Array<{ path: string; content: string }> = [
    {
      path: path.join(
        repoRoot,
        "packages/devsh/internal/models/claude_generated.go",
      ),
      content: formatGoSource(generateDevshClaudeModelsGo()),
    },
    {
      path: path.join(
        repoRoot,
        "packages/agent-sdk/src/claude-pricing.generated.ts",
      ),
      content: generateAgentSdkClaudePricingTs(),
    },
    {
      path: path.join(
        repoRoot,
        "packages/agent-sdk-python/src/cmux_agent_sdk/claude_pricing_generated.py",
      ),
      content: generateAgentSdkClaudePricingPy(),
    },
  ];

  let ok = true;
  for (const target of targets) {
    if (!writeOrCheckFile(target.path, target.content)) {
      ok = false;
    }
  }

  if (!ok) {
    process.exit(1);
  }

  if (CHECK_ONLY) {
    console.log("[sync-claude-model-artifacts] All generated artifacts are up to date.");
  }
}

main();
